# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

general:
  branches:
    ignore:
      - gh-pages

orbs: 
  browser-tools: circleci/browser-tools@1.4.4
  jobs:
    test:
      steps:
        - browser-tools/install-browser-tools:
            chrome-version: 116.0.5845.96
            replace-existing-chrome: true
            # TODO: remove until: https://github.com/CircleCI-Public/browser-tools-orb/issues/75


defaults: &defaults
  docker:
    - image: cimg/node:18.13.0-browsers
      environment:
        CHROME_BIN: /usr/bin/google-chrome

jobs:
  say-hello:
    <<: *defaults
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  test:
    <<: *defaults
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: 116.0.5845.96
          replace-existing-chrome: true
      - run: npm ci
      #- run: npm run ng -- test components 
  build:
    <<: *defaults
    steps:
      - checkout
      #- run: npm run lint
      - run:
          name: "version"
          command: |
            sh ./version.sh ${CIRCLE_BUILD_NUM} ${CIRCLE_BRANCH}
      - run:
          name: "version @muziehdesign/angularcore"
          command: |
            sh ./../../version.sh ${CIRCLE_BUILD_NUM} ${CIRCLE_BRANCH}
          working_directory: ./projects/core
      - run: npm ci
      - run: npm run ng -- build core
      - store_artifacts:
          path: /dist/core
          destination: muziehdesign/angularcore
      - store_artifacts:
          path: /dist/muziehdesign/ui
          destination: muziehdesign/ui
      - persist_to_workspace:
          root: .
          paths:
            - dist
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: "npm publish prep"
          command: |
            touch .npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: 
          name: 'npm publish'
          command: |
            if [ "$BRANCH" = "master" ] || [ "$BRANCH" = "develop" ] ||  [[ "$BRANCH" = \release\/* ]]; then
              echo "publishing non-beta package"
              npm publish ./dist/components
              npm publish ./dist/design
            else
              echo "publishing beta package"
              npm publish ./dist/components --tag beta
              npm publish ./dist/design --tag beta
            fi
            # npm publish ./dist/muziehdesign/ui --tag alpha

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  publish:
    jobs:
      - say-hello:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          requires:
            - say-hello
      - build:
          requires:
            - say-hello
      - publish:
          requires:
            - test
            - build

      
